apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts-check-pr-title.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "charts-check-pr-title.name" . }}
    helm.sh/chart: {{ include "charts-check-pr-title.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "charts-check-pr-title.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "charts-check-pr-title.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GITHUB_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "charts-check-pr-title.secretname" . }}
                  key: shared-secret
            - name: GITHUB_REPO_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "charts-check-pr-title.secretname" . }}
                  key: github-repo-name
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "charts-check-pr-title.secretname" . }}
                  key: github-token
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
