{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "charts-check-pr-title.secretname" . }}
  labels:
    app.kubernetes.io/name: {{ include "charts-check-pr-title.name" . }}
    helm.sh/chart: {{ include "charts-check-pr-title.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  shared-secret: {{ default "" .Values.secrets.sharedSecret | b64enc | quote }}
  github-repo-name: {{ default "" .Values.secrets.repoName | b64enc | quote }}
  github-token: {{ default "" .Values.secrets.ghToken | b64enc | quote }}
{{- end }}